FROM node:alpine

WORKDIR /app

EXPOSE 3000

COPY package* ./

ENV NODE_ENV=development

RUN npm install

COPY . ./

CMD [ "npm", "run", "start" ]

# docker run -it --rm -v $(pwd):/app -p 8080:8080 crypto-dude